name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: |
        mvn clean install
      continue-on-error: false  # Ensure the job fails if this step fails

    - name: Run Tests
      run: |
        mvn test
      continue-on-error: false  # Ensure the job fails if tests fail
