name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  # This will run the workflow on Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Specify JDK 17
          distribution: 'temurin'  # Specify the distribution
  
      - name: Build with Maven
        run: mvn install  # Build the project using Maven
  
      - name: Run Tests
        run: mvn test  # Run tests using Maven

